### ISSUE TITLE
Non stationary kernel

### ISSUE THREAD

**Issue by shenggong1996** [b-shields/edbo#15]
Does EDBO support non-stationary kernel like linear kernel?

**Comment by b-shields** [comment]
On a high level, EDBO allows any surrogate model you would like. To support most acquisition functions (except for TS which requires posterior sampling) you need to implement a model class with fit, predict, and variance methods (see https://github.com/b-shields/edbo/blob/master/edbo/models.py as an example). To change the GP kernel to linear you can add a new base model (check https://github.com/b-shields/edbo/blob/master/edbo/base_models.py) that uses GPyTorch's linear kernel (https://docs.gpytorch.ai/en/stable/kernels.html#linearkernel) and swap it into edbo.models.GP_Model.

If you really would just like to try a linear kernel I would suggest checking out the already implemented Bayesian linear model with ARD (https://b-shields.github.io/edbo/models.html#edbo.models.Bayesian_Linear_Model). This is equivalent to a GP + a linear kernel except for the training details.
